### PR TITLE
chore: upgrade to coder/websocket 1.8.12

### PR DESCRIPTION
**Pull request by spikecurtis**
Migrates to coder/websocket from nhooyr/websocket and upgrades to v1.8.12.

Also retires and removes `wsconn` which was a fork of `websocket`'s implementation of `NetConn` to work around a bug that has been fixed.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#65** <a href="https://app.graphite.dev/github/pr/coder/tailscale/65?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/tailscale/65?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by spikecurtis** [comment]
This is a prereq to moving coder/coder over to coder/websocket, so that we don't build and include two separate websocket libraries.

**Review by deansheather — APPROVED** [review]

**Comment by spikecurtis** [comment]
### Merge activity

* **Dec 3, 6:20 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/coder/tailscale/65).

**Comment by Emyrk** [comment]
@spikecurtis we still reference wsconn in coder/coder 

https://github.com/coder/coder/blob/main/tailnet/derp.go#L13

**Comment by spikecurtis** [comment]
> @spikecurtis we still reference wsconn in coder/coder
> 
> https://github.com/coder/coder/blob/main/tailnet/derp.go#L13

Not anymore!

**Pull request merged**
